INSERT INTO Parties (name, id) VALUES ("Democrat", "1")
,("None", "2")
,("Republican", "3")
,("Libertarian", "5")
,("Independent", "6")
,("Constitution Party", "7")
,("Talk show host", "9")
,("Democratic Farmer-Labor", "10")
,("Rhode Island Tea Party", "67")
,("Government body", "68")
,("Senate Democrats", "69")
,("State official", "14")
,("Newsmaker", "15")
,("Organization", "16")
,("Republican", "70")
,("Columnist", "18")
,("Labor leader", "19")
,("Tea Party member", "20")
,("Education official", "71")
,("county commissioner", "22")
,("Activist", "23")
,("Law enforcement official", "72")
,("Ocean State Tea Party in Action", "57")
,("Business leader", "58")
,("Philadelphia Daily News", "73")
,("Journalist", "64")
,("Moderate Party", "8")
,("Liberal Party of Canada", "75")
,("Green", "76");