INSERT INTO Subjects (id, description, name) VALUES ("11", "", "Abortion")
,("113", "", "Afghanistan")
,("309", "", "After the Fact")
,("122", "", "Agriculture")
,("186", "", "Alcohol")
,("210", "", "Animals")
,("124", "", "Autism")
,("45", "", "Bankruptcy")
,("166", "", "Baseball")
,("149", "", "Bipartisanship")
,("12", "", "Bush Administration")
,("154", "", "Campaign Finance")
,("13", "", "Candidate Biography")
,("116", "", "Cap and Trade")
,("111", "", "Census")
,("127", "", "Children")
,("180", "", "China")
,("196", "", "City Budget")
,("203", "", "City Government")
,("117", "", "Civil Rights")
,("313", "<p>Most scientists agree that climate change is real and humans are causing it. The figure that&rsquo;s widely cited is 97 percent of climate scientists, and it appears in at least&nbsp;<a href='http://www.politifact.com/truth-o-meter/statements/2015/sep/02/rick-santorum/santorum-un-climate-head-debunked-widely-cited-97-/'>three peer-reviewed surveys</a>.&nbsp;<a href='http://www.politifact.com/virginia/statements/2016/apr/04/don-beyer/don-beyer-says-97-percent-scientists-believe-human/'>Plenty of other studies</a>&nbsp;report overwhelming majorities of experts (in the 90 percent range) and at least&nbsp;<a href='http://climate.nasa.gov/scientific-consensus/'>18 scientific associations</a>&nbsp;agree.</p>
", "Climate Change")
,("254", "", "Congress")
,("187", "", "Congressional Rules")
,("28", "", "Consumer Safety")
,("101", "", "Corporations")
,("255", "<p>We strive to make our work completely accurate. When we make a mistake, we correct it and note it on the original item. If the mistake is so significant that it requires us to change the ruling, we will do so. Readers who see an error should contact the writer or editor. Their names are listed on the right side of every Truth-O-Meter item. Clicking on their names will take you to their bio pages, where you can find their email addresses. Read more about our corrections policies in our <a href='http://www.politifact.com/truth-o-meter/article/2013/nov/01/principles-politifact-punditfact-and-truth-o-meter/'>Principles of the Truth-O-Meter</a>.</p>
", "Corrections and Updates")
,("171", "", "County Budget")
,("209", "", "County Government")
,("38", "", "Crime")
,("177", "", "Criminal Justice")
,("321", "", "Death Penalty")
,("302", "", "Debates")
,("296", "", "Debt")
,("183", "", "Deficit")
,("129", "", "Disability")
,("130", "", "Diversity")
,("161", "", "Drugs")
,("316", "", "Ebola")
,("4", "", "Economy")
,("32", "", "Education")
,("21", "", "Elections")
,("10", "", "Energy")
,("5", "", "Environment")
,("35", "", "Ethics")
,("323", "<p>There&rsquo;s an interesting discussion happening now about the spread of fake news on the Internet and what companies like Facebook, Google and Twitter, among others, should do to stop it.</p>

<p>That&rsquo;s a healthy conversation to have, and one we hope continues in the weeks and months ahead.</p>

<p>But that doesn&rsquo;t mean we can&rsquo;t do something now. Here at PolitiFact, we&rsquo;re beefing up our coverage of fake news to help our readers better sort out fact from fiction on their social media feeds.</p>

<p>The claims can be about anything -- politics, entertainment, a fishy-sounding medical cure.</p>
", "Fake news")
,("119", "", "Families")
,("33", "", "Federal Budget")
,("153", "", "Financial Regulation")
,("319", "", "Fires")
,("112", "", "Florida")
,("162", "", "Florida Amendments")
,("322", "", "Food")
,("158", "", "Food Safety")
,("27", "", "Foreign Policy")
,("170", "", "Gambling")
,("204", "", "Gas Prices")
,("118", "", "Gays and Lesbians")
,("131", "", "Government Efficiency")
,("213", "", "Government regulation")
,("19", "", "Guns")
,("26", "<p><a href='http://www.politifact.com/truth-o-meter/article/2015/mar/20/federal-health-care-law-what-came-true-and-what-di/'>Predictions about the federal health care law, Obamacare, were a dime a dozen back in 2010</a>. Supporters contended that virtually everyone around the country would soon have access to affordable insurance. Opponents said the law would cost a fortune by adding to the national debt and killing jobs.&nbsp;Actually, none of those things have happened. The law has taken twists and turns, moving off course from where everyone thought it would be.&nbsp;Once expected to insure 32 million new Americans by the end of the decade, the projected target was downgraded to 27 million by 2015.&nbsp;Unforeseen developments, like significant changes in health cost trends and a sweeping Supreme Court decision on Medicaid expansion, have meant the insurance provisions in the law will cost $139 billion less over the rest of the decade. That has quieted some critics who expected massive, deficit-inflating costs. The law has steadily navigated toward its overall goal of decreasing the number of uninsured Americans, without dramatically disrupting the overall health care industry, for better or worse. Yet.&nbsp;</p>

<p>&quot;The whole thing has been in much slower motion that what was predicted,&quot; said Michael Tanner, health care analyst with the libertarian Cato Institute. &quot;Whether you thought something good was going to happen or something bad, you sort of thought it would have happened by now. Instead, it&rsquo;s just been creeping along.&quot;&nbsp;</p>
", "Health Care")
,("42", "", "History")
,("132", "", "Homeland Security")
,("318", "", "Homeless")
,("106", "", "Housing")
,("105", "", "Human Rights")
,("188", "", "Hunger")
,("23", "<p>Amnesty,&nbsp;<a href='http://www.cbsnews.com/news/romney-on-immigration-im-for-self-deportation/'>self-deportation</a>, a&nbsp;<a href='http://www.theguardian.com/us-news/2015/jun/28/donald-trump-mexico-immigration-presidential-campaign'>wall</a>. Politicians have plenty of ideas to fix America&rsquo;s immigration system. But where does rhetoric leave reality?</p>
", "Immigration")
,("184", "", "Income")
,("133", "", "Infrastructure")
,("1", "", "Iraq")
,("211", "", "Islam")
,("48", "", "Israel")
,("3", "", "Job Accomplishments")
,("175", "", "Jobs")
,("156", "", "Kagan Nomination")
,("317", "", "Katrina")
,("192", "", "Labor")
,("34", "", "Legal Issues")
,("291", "", "Lottery")
,("310", "", "Marijuana")
,("134", "", "Marriage")
,("212", "", "Medicaid")
,("50", "", "Medicare")
,("157", "", "Message Machine 2010")
,("219", "", "Message Machine 2012")
,("311", "", "Message Machine 2014")
,("30", "", "Military")
,("312", "", "Natural Disasters ")
,("165", "", "Negative Campaigning")
,("214", "", "New Hampshire 2012")
,("320", "<p>Nightlife</p>
", "Nightlife")
,("135", "", "Nuclear")
,("167", "", "Obama Birth Certificate")
,("218", "", "Occupy Wall Street")
,("155", "", "Oil Spill")
,("36", "", "Patriotism")
,("217", "", "Pensions")
,("136", "", "PolitiFact's Top Promises")
,("194", "", "Polls and Public Opinion")
,("52", "", "Pop Culture")
,("293", "", "Population")
,("29", "", "Poverty")
,("114", "", "Privacy")
,("202", "", "Public Health")
,("173", "", "Public Safety")
,("137", "", "Public Service")
,("104", "", "Pundits")
,("100", "", "Recreation")
,("207", "", "Redistricting")
,("109", "", "Regulation")
,("9", "", "Religion")
,("102", "", "Retirement")
,("139", "", "Science")
,("304", "", "Second Term Promise")
,("256", "", "Sexuality")
,("140", "", "Small Business")
,("141", "", "Social Security")
,("110", "", "Sotomayor Nomination")
,("142", "", "Space")
,("216", "", "Sports")
,("120", "", "State Budget")
,("208", "", "State Finances")
,("147", "", "States")
,("150", "", "Stimulus")
,("108", "", "Supreme Court")
,("294", "", "Tampa Bay 10 News")
,("8", "", "Taxes")
,("115", "", "Technology")
,("37", "", "Terrorism")
,("152", "", "The Colbert Report")
,("151", "", "This Week - ABC News")
,("201", "", "Tourism")
,("143", "", "Trade")
,("107", "", "Transparency")
,("44", "", "Transportation")
,("206", "", "Unions")
,("144", "", "Urban")
,("51", "", "Veterans")
,("159", "", "Voting Record")
,("197", "", "Water")
,("258", "", "Wealth")
,("198", "", "Weather")
,("221", "", "Welfare")
,("146", "", "Women")
,("103", "", "Workers");